"""Instruction prompts for the Multi-Agent Orchestration demo."""

from .instructions import (
    CODE_WRITER_INSTRUCTION,
    CONTENT_SYNTHESIZER_INSTRUCTION,
    CREATIVE_WRITER_INSTRUCTION,
    CRITIC_INSTRUCTION,
    FINAL_EDITOR_INSTRUCTION,
    REVISOR_INSTRUCTION,
    TECHNICAL_RESEARCHER_INSTRUCTION,
    TECHNICAL_WRITER_INSTRUCTION,
    TOPIC_ANALYZER_INSTRUCTION,
    TREND_RESEARCHER_INSTRUCTION,
)

__all__ = [
    "TOPIC_ANALYZER_INSTRUCTION",
    "TREND_RESEARCHER_INSTRUCTION",
    "TECHNICAL_RESEARCHER_INSTRUCTION",
    "CREATIVE_WRITER_INSTRUCTION",
    "TECHNICAL_WRITER_INSTRUCTION",
    "CODE_WRITER_INSTRUCTION",
    "CONTENT_SYNTHESIZER_INSTRUCTION",
    "CRITIC_INSTRUCTION",
    "REVISOR_INSTRUCTION",
    "FINAL_EDITOR_INSTRUCTION",
]
